name: "Generate Documentation"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = file://${{ github.workspace }}/store-cache?trusted=true
    - name: Set up store cache
      uses: actions/cache@v2
      with:
        path: store-cache
        key: nix-store

    - name: Generate documentation
      run: nix build .#data-list-unweave.doc

    - name: Prepare documentation
      run: |
        git switch doc
        rm -rf docs
        cp -r result-doc/share/doc/*/html docs

    - name: Upload documentation
      uses: EndBug/add-and-commit@v9
      with:
        add: docs
        message: Upload documentation
        default_author: github_actions
        committer_name: GitHub Actions
        committer_email: actions@github.com
